### ISSUE TITLE
Constructor of compose component called twice

### ISSUE THREAD

**Issue by eliavmaman** [aurelia/dependency-injection#86] opened 2016-04-14 11:18 UTC
Hey
I have app.html the have compose element game
` <compose view-model="./games"></compose>`

in app.js
`@inject(Games)
export class App{
constructor(games) {
        this.games = games;
    }
}
`

why class game constructor called twice???

**Comment by eliavmaman** [comment] 2016-04-18 07:05
is there anyone who can answer that please?

**Comment by z-brooks** [comment] 2016-04-18 07:58
If you only want a single instance of that vm try the `@singleton` decorator

```es6
import {singleton} from 'aurelia-framework';
// ...
@singleton()
export class Games { /* ... */ }
```

**Comment by EisenbergEffect** [comment] 2016-04-18 12:27
Can you create a repro for us and attach it here?

**Comment by stsje** [comment] 2016-04-18 14:18
My guess would be that the composed Games component and the one you inject aren't the same instance. There's no link between the two.

**Comment by eliavmaman** [comment] 2016-04-19 07:06
@stsje 
You actually right, based of Aurelia documentation, to use `compose`,
 you need to  ` <require from="./games"></require>`  to get the view (html) of games.
does compose element create new instance of game?!?!?!

and in the class as i mentioned , i'm injecting games obj , so i could use it's functions (obvious) in app class.

**Comment by EisenbergEffect** [comment] 2016-04-19 13:24
@stsje You are getting a bit confused about different features. If you have an existing instance of games, you can compose that with a binding. If you don't you can use the module id with compose. If it's static, you can use require to bring in the element and then use the element. It all depends on what you want to accomplish. I'm going to close this issue since it's not a bug, but please continue to add some more information here so we can advise you.

**Closed by EisenbergEffect** 2016-04-19 13:24 UTC
