### ISSUE TITLE
Container.get() looses type safety

### ISSUE THREAD

**Issue by antanas-arvasevicius** [aurelia/dependency-injection#70] opened 2016-01-10 10:38 UTC
Hi,
in TypeScript definitions there is class `Container`, `get` method definition as:
``get(key: any): any;``

It should be like this:
```
    get<T>(key: {new(...args): T}): T;
    get(key: any): any;
```

then  we can write more fluently and have typing:

``
container.get(SomeRepository).findById(123);
``
instead of:  ``var repo = <SomeRepository>container.get(SomeRepository);``

I don't know how this container is exactly used, but maybe there is no need for `key:any, return any` at all.

You can find more info about this kind of type definitions at:

https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Generics.md

**Comment by EisenbergEffect** [comment] 2016-01-10 13:49
Well, we could do something like that, but it wouldn't be accurate. The reason is that the key can be anything and that can really return anything. It just so happens that the most common thing to do is return the same types that was requested. But, you could use a string key if you had mapped that to some Type or instance.

**Comment by antanas-arvasevicius** [comment] 2016-01-10 14:47
TypeScript support multiple definitions of the same function/method. So if user will do something like  container.get(SomeClass)  it will use first definition, and  if it will use
container.get("some_string")  it will use second `get` definition, because type string is not `newable` and first definition wont match.

Btw, it could be possible to use  strings as key and also get correct types, here is example how it's achieved: 
https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L2090

**Comment by michalstocki** [comment] 2016-02-02 20:58
@antanas-arvasevicius I would really enjoy better typing of the `container.get()` method however, the problem is not as simple as you described.

In our tests we often do following:
```typescript
class SomeClass {
}

// in a test for another class which uses SomeClass as a dependency:
container.registerInstance(SomeClass, mockClass);

container.get(SomeClass); // this will return mockClass instead of an instance of SomeClass
```

**Comment by EisenbergEffect** [comment] 2016-02-02 21:34
The "key" can be anything and can resolve to anything, so we can't infer types there. I think that we could probably do something custom in our d.ts though to add some sort of generics-based override that makes this more convenience. I'm not a TS expert though. Thoughts on that idea?

**Comment by antanas-arvasevicius** [comment] 2016-02-03 09:52
@michalstocki Your example is not valid because if we are writing  `container.get(SomeClass)` we actually need an object which conforms to this SomeClass interface, if we call that, we don't care about specific class which will be returned, over wise it's a design smell in your code.

So we actually need to declare in TypeScript this rule: 
if we pass, in get(..) parameter a constructor of object T, get() should return object T

This declaration says so: `get<T>(key: {new(...args): T}): T;`

@EisenbergEffect  Typescript can have a multiple declarations of the same method/function, it will look up from top to bottom and will choose automatically which will match first.
so writing to .d.ts:
```
get<T>(key: {new(...args): T}): T;
get(key: any): any;
```

is valid in TypeScript. And it solves first problem. Second problem, that you can pass a string and get an any kind of object is not resolvable within TypeScript typing system.
But if you know some core specific service which must return object with known interface you can do as so:

```
get(key: "container"): Container;
get(key: "kernel"): CoreKernel;
get(key: "front_controller"): IFrontController;

get<T>(key: {new(...args): T}): T;
get(key: any): any;
```

and it's valid and documented TypeScript :) and you can get an autocomplete of IDE, type inference and also benefits from TypeScript compiler step, as if you write: 
`let action = Container.instance.get('front_controller').getKKontrodjk('')` it won't compile.
Without proper typing it is actually the same as working in plain JavaScript.

And you know, if core classes of framework, do have proper typing information with type parameters, generics and so it just flows to all application codes automatically, and programmers do not need to explicitly annotate any parameters or functions and still get full strong type checking of compiler.

And btw, what I was struggled about, TypeScript type system is structural typing, so interface names is irrelevant as in other languages, they completely match if it's definitions will has same fields with compatible types. So interface names is just used for readability purposes only.

**Comment by godrose** [comment] 2016-03-22 12:30
@EisenbergEffect  @antanas-arvasevicius Any updates on this. 
How do I enable type-safe resolution in my code?
I've tried adding the ``get<T>(key: {new(...args): T}): T;`` line but it didn't work.

**Comment by EisenbergEffect** [comment] 2016-03-22 12:35
I believe we will be able to add generics to our d.ts files soon.
FYI The new constraint isn't required and the kay and the output don't have to be the same value. Key can be anything and it can internally map to anything. It's just common that they are both the same.

**Comment by EisenbergEffect** [comment] 2016-03-22 12:38
I think, my greater concern is why people are accessing the container's `get` method at all. That is typically an example of the "Service Locator Anti-pattern". If you have lots of direct container access in your code, that's definitely a deeper issue that needs to be solved. I'd like to hear some use cases for the direct container `get` invocation. The only thing I can come up with would be in infrastructure.

**Comment by godrose** [comment] 2016-03-22 12:45
I'm aware of this anti-pattern.
When I started defining the interface for IoC container I didn't include any resolution methods there. None at all. However as i developed more and more apps i identified use cases where I had to create new instances of view models. Typically I had two options: 1) new it up 2) resolve from the container.
Newing is simpler but then you have to inject all dependencies into the parent which contaminates its constructor and makes these dependencies look like they're also parent's dependencies. And of course you lose all the lifetime management,
Resolving from the container has one major drawback - Service Locator anti-pattern.
The direct access is isolated in one place : ``ViewModelCreatorService`` and nowhere else.

**Comment by godrose** [comment] 2016-03-22 12:48
imagine a case where you have collection of POCOs(POJOs/DTOs) which arrive from the server.
Then you create the respective models from these objects, adding change tracking, validation, error handling concerns. Then you wrap the models with the respective object view models, adding commanding, possibly another advanced scenarios (DP bridge, etc.). All these object view models have to be created dynamically and fed with the data. Again, i can new 'em up but then I lose all the goodies of the IoC.

**Comment by EisenbergEffect** [comment] 2016-03-22 12:52
In our case, we provide "resolvers". Which is a way to get around this pattern. I'll write some DI docs in the next week or so....need to get this information out. Apologies for the delay in that.

**Comment by EisenbergEffect** [comment] 2016-03-22 12:54
Also, I do think using the container, as part of infrastructure, is ok. After all, that's what Aurelia does. However, when that leaks out of infrastructure code and into other areas of the app is when it tends to become a problem.

For the d.ts, it may be time for us to take our generated d.ts as a starting point, stop generating and then manually edit it to our liking to add some of these better-typed apis. I'm not sure. What does this group think?

**Comment by godrose** [comment] 2016-03-22 12:55
> In our case, we provide "resolvers". Which is a way to get around this pattern. I'll write some DI docs in the next week or so....need to get this information out. Apologies for the delay in that.

That would be very nice. I'm not really an expert in aurelia's implementation of IoC and that would be very helpful. 
Thanks for the great job on this project and all other contributions (like Caliburn.Micro )

**Closed** 2016-06-14 17:53 UTC
Labels: documentation

**Comment by unional** [comment] 2016-06-17 23:15
I'm also using `container.get()` directly. In my case, I did something else to get around the service locator anti-pattern.

In either case (user should use `resolver` or `container.get()`), it would still be great if the typings is updated to (same as @antanas-arvasevicius described, with the `args` explicitly typed):

```ts
    get<T>(key: new(...args: any[]) => T): T;
    get(key: any): any;
```

**Comment by aluanhaddad** [comment] 2016-11-07 03:41
@unional I was about to file this issue, glad I used search. I keep adding this to my `aurelia-dependency-injection.d.ts`, whenever I update it
```ts
    get<T>(key: new (...args) => T): T;
```
