### ISSUE TITLE
Enhance debugging/logging possibilities (opt-in)

### ISSUE THREAD

**Issue by ZoolWay** [aurelia/dependency-injection#124] opened 2016-09-09 14:21 UTC
**I'm submitting a feature request**
- **Library Version:**
  aurelia-framework 1.0.1

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  6.5.0
- **NPM Version:**
  3.10.5
- **JSPM OR Webpack AND Version**
  JSPM 0.16.39
- **Browser:**
  all | Chrome 52
- **Language:**
  all | TypeScript 2.0.1

**Current behavior:**
At the moment aurelia-dependency-injection does not log anything. I have run into the `badKeyError` multiple times in the last weeks (_key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?_) and those are the hardest to debug. I am often several instances deep in the stack trace to find out what's wrong. The last time I had some kind of circular dependency, this time a problem only occuring when bundled (not solved yet).

**Expected/desired behavior:**
It would be very nice if I could opt-in to some detailed logging for every registration with a container, every child container creation, every resolve attempt. When resolving dependencies the log could count the stack depth and intend the log message so you might be able to see the tree when looking at the messages.

This could be a switch (maybe aurelia configuration setting in main.ts?) or exchanging the module for an _aurelia-dependency-injection-debug_ variant.

Also if anyone else has hints how to debug DI problem scenarios I appreciate every insight.

**What is the motivation / use case for changing the behavior?**
Debugging DI is especially hard and I believe I am not the only one feeling this way. I don't see how the Chrome dev tools are helpful in any way.

**Comment by EisenbergEffect** [comment] 2016-09-30 06:43
I think this is a great idea, if we can do it as an opt-in that doesn't affect production performance. @ZoolWay Do you have any interest in putting together a PR to accomplish this?

**Comment by ZoolWay** [comment] 2017-05-15 07:03
Sorry I did not comment that time. At this moment I do not feel confident enough to find a nice solution. I am working a new DI problem, though...

**Comment by huochunpeng** [comment] 2018-03-14 00:01
@Alexander-Taran as long as using aurelia logger to log at debug or info level, it would not affect production perf.

But that is assuming https://github.com/aurelia/framework/pull/851 was accepted.

**Comment by fkleuver** [comment] 2018-03-14 01:44
I think what the DI really needs is interception capabilities. For example via "beforeResolve" and "afterResolve" hooks. Then logging could easily be plugged in to that, as can other things.

**Comment by huochunpeng** [comment] 2018-03-14 01:47
@fkleuver it looks like you are in good position to compose a PR. 👍

**Comment by fkleuver** [comment] 2018-03-14 01:54
@EisenbergEffect do you think interception would fit in this major version or should that be a vNext thing?

**Comment by EisenbergEffect** [comment] 2018-03-14 03:16
I'm nervous about adding something like this to the DI, since it could massively affect perf. We'd need to benchmark a complex component hierarchy creation to be sure we weren't introducing a perf regression.

**Comment by fkleuver** [comment] 2018-03-14 05:48
The only addition to the current api's execution path (without interception) would be a single `if` branch to check if there are interceptors. I doubt that would have any measurable performance impact.

Of course with interceptors enabled there would be the impact of invoking those interceptors which entirely depends on the code that they run. But this is something users can anticipate and be okay with, and won't affect existing code.

**Comment by Alexander-Taran** [comment] 2019-01-07 18:01
@EisenbergEffect should we consider this for vCurrent as well?

**Comment by EisenbergEffect** [comment] 2019-01-07 18:05
It's much more difficult to do this in vCurrent. It's already in place for vNext.

**Comment by EisenbergEffect** [comment] 2019-01-07 18:06
I'd prefer not to add new features to vCurrent for now, esp. in a core component like DI unless we absolutely have to. Changes there could have big effects.

**Comment by Alexander-Taran** [comment] 2019-01-07 21:20
@EisenbergEffect then let's close this one

**Closed** 2019-01-07 21:20 UTC
Labels: enhancement, help wanted
