### ISSUE TITLE
Version 1.4.0 does not contain the dist directory

### ISSUE THREAD

**Issue by zenorbi** [aurelia/dependency-injection#166] opened 2018-06-18 07:35 UTC
**I'm submitting a bug report**

* **Library Version:**
1.4.0

* **Node Version:**
10.4.1

* **NPM Version:**
6.1.0

* **JSPM OR Webpack AND Version**
jspm@0.17.0-beta.47

* **Language:**
all

**Current behavior:**
The released 1.4.0 version does not contain "dist" directory, and as such cannot be used neither from node, nor from jspm as package.json points to the "dist" directory which does not exist.

**Comment by fracz** [comment] 2018-06-18 08:51
Also, the typings fail to download the types because of this change:

> Unable to read typings for "aurelia-dependency-injection". The author of "aurelia-dialog" needs to check the entry paths in "typings.json" are up to date
 caused by https://raw.githubusercontent.com/aurelia/dependency-injection/master/dist/aurelia-dependency-injection.d.ts/index.d.ts responded with 404, expected it to equal 200

**Comment by pragmaproducts** [comment] 2018-06-18 09:08
when installing packages, this breaks everything.
jspm does not have a aurelia-dependency-injector@version.js file nor does it contain the dist.
!($*^(!^@ so much for testing your stuff.

**Comment by olibanjoli** [comment] 2018-06-18 10:58
+1

package.json: 

`  "main": "dist/commonjs/aurelia-dependency-injection.js",`

but the `dist` folder is in the `doc` folder

this breaks aurelia-cli

**Comment by EisenbergEffect** [comment] 2018-06-18 14:44
Released 1.4.1. Please give that a try.

**Comment by EisenbergEffect** [comment] 2018-06-18 16:05
Closing since I've received confirmation from a few sources that the issue is fixed. Again, apologies for the inconvenience. Not sure what happened there. I'll keep a close eye on it for future releases.

**Closed by EisenbergEffect** 2018-06-18 16:05 UTC
